# Candace Savonen Aug 2021
# Updated Kate Isaac Nov 2025
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  - files:
      - source: .github/workflows/
        dest: .github/workflows/
        deleteOrphaned: true
        exclude: |
          send-updates.yml
          test-send-updates.yml
          docker-test.yml
      - source: .github/workflows/delete-preview.yml
        dest: .github/workflows/delete-preview.yml
      - source: .github/workflows/render-all.yml
        dest: .github/workflows/render-all.yml
      - source: .github/workflows/pull_request.yml
        dest: .github/workflows/pull_request.yml
      - source: .github/workflows/check-url.yml
        dest: .github/workflows/check-url.yml
      - source: config_automation.yml
        dest: config_automation.yml
      - source: _brand.yml
        dest: _brand.yml
      - source: index.qmd
        dest: index.qmd
      - source: styles.css
        dest: styles.css
  # Repositories to receive changes
    repos: |
      opencasestudies/bio-ocs-et-single-cell
      opencasestudies/bio-ocs-et-ai-diffusion
      opencasestudies/bio-ocs-et-spatial-expression
      opencasestudies/bio-ocs-et-spatial-latent-variable
      opencasestudies/bio-ocs-et-temporal
      opencasestudies/bio-ocs-bp-containers
      opencasestudies/bio-ocs-bp-version-control
      opencasestudies/bio-ocs-bp-big-data
###ADD NEW REPO HERE following the format above#

### These are custom groups for syncing -- not all files needs to be synced # will update later
  # - files:
  #   - source: config_automation.yml
  #     dest: config_automation.yml
  #   - source: .github/workflows/pull-request.yml
  #     dest: .github/workflows/pull-request.yml
  #   - source: scripts/spell-check.R
  #     dest: scripts/spell-check.R
  #   repos: |
  #     jhudsl/Baltimore_Community_Course
