# Candace Savonen Aug 2021
# Updated Kate Isaac Nov 2025
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  - files:
      - source: assets/
        dest: assets/
        deleteOrphaned: true
      - source: .github/workflows/delete-preview.yml
        dest: .github/workflows/delete-preview.yml
      - source: .github/workflows/render-all.yml
        dest: .github/workflows/render-all.yml #render-all instead of render-site even though it is just a website because we may need to add action steps for leanpub rendering in the future
      - source: .github/workflows/pull_request.yml
        dest: .github/workflows/pull_request.yml
      - source: .github/workflows/check-url.yml
        dest: .github/workflows/check-url.yml
      - source: .github/workflows/docker-test.yml
        dest: .github/workflows/docker-test.yml
      - source: config_automation.yml
        dest: config_automation.yml
      - source: _brand.yml
        dest: _brand.yml
      - source: styles.css
        dest: styles.css
  # Repositories to receive changes
    repos: |
      opencasestudies/ocs-bio-single-cell
      opencasestudies/ocs-bio-ai-deep-learning
      opencasestudies/ocs-bio-spatial-transcriptomics
      opencasestudies/ocs-bio-latent-variable
      opencasestudies/ocs-bio-temporal
      opencasestudies/ocs-bio-biocontainers
      opencasestudies/ocs-bio-version-control
      opencasestudies/ocs-bio-big-data
###ADD NEW REPO HERE following the format above#
