---
title: "**Biomedical Open Case Studies: {Title}**"
include-sections:
  stat-los: false
  data-import: true
  data-exploration: false
  data-wrangling: true
  data-viz: true
  data-analysis: true
params:
  wordcount: |
    {{< words-body >}}
---

<!--
  Update the various qmd documents below with each component of a Bio-OCS case study.
  Besides filling in the title in the header of this document, no other changes should be necessary within this file.
  You may chose to remove the data exploration step if it's not necessary.
-->

{{< include _main_image.qmd >}}

{{< include _ocs_frontmatter.qmd >}}

<details><summary>Estimated **reading time** and this material's **readability score**</summary>

{{< words-body >}}

```{r, echo = FALSE, warning = FALSE}
library(stringr)
wordcount <- params$wordcount
print(wordcount)
print(as.numeric(as.character(wordcount)))


estimate <- round(as.numeric(wordcount) / 200, 0)
```

**Reading Time: ** `{r} estimate ` minutes



The total reading time for this case study is calculated by finding a word count using a [quarto extension](https://github.com/andrewheiss/quarto-wordcount) and estimating time based on an average adult reading speed of 200 words per minute.

***

**Readability Score: **


***

</details>

{{< include _cite.qmd >}}

{{< include _motivation.qmd >}}

{{< include _main_question.qmd >}}

{{< include _los.qmd >}}

{{< include _packages.qmd >}}

{{< include _context.qmd >}}

{{< include _data_description.qmd >}}

{{< include _limitations.qmd >}}

{{< include _bioethics.qmd >}}

::: {.content-hidden unless-meta="include-sections.data-import"}

{{< include _data_import.qmd >}}

:::

::: {.content-hidden unless-meta="include-sections.data-exploration"}

{{< include _data_exploration.qmd >}}

:::

::: {.content-hidden unless-meta="include-sections.data-wrangling"}

{{< include _data_wrangling.qmd >}}

:::

::: {.content-hidden unless-meta="include-sections.data-viz"}

{{< include _data_visualization.qmd >}}

:::

::: {.content-hidden unless-meta="include-sections.data-analysis"}

{{< include _data_analysis.qmd >}}

:::

{{< include _summary.qmd >}}

{{< include _suggested_hw.qmd >}}

{{< include _additional_info.qmd >}}

## **Session Info**
***

```{r}
devtools::session_info()
```

{{< include _acknowledgements.qmd >}}
